### ISSUE TITLE
Broken End Island

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/addon-bskyblock#30] opened 2018-12-18 17:24 UTC
**Description**
First End island is generated with the end return portal on it.

**Steps to reproduce the behavior:**
1. Create new server with only BentoBox plugin and bSkyBlock addon.
2. Go to the END in first island.
3. User is in GM3 and on top of island is Return Portal.

**Expected behavior**
I think, if there is the return portal, then it should not be on top of island, but near it... And it must be for each user.

**Screenshots**
https://imgur.com/l3L2Zsi

**Server Information:**
craftbukkit 1.13.2 :
 - Flat file
 - MacOS / Windows
 - Java Version: Java 8
 - BentoBox version: 0.17.0
 - Addons installed?  bSkyblock 0.5.0

**Additional context**
This issue relates to #377.

**Comment by Poslovitch** [comment] 2018-12-18 17:31
Duplicate of https://github.com/BentoBoxWorld/bentobox/issues/223

**Closed by Poslovitch** 2018-12-18 17:31 UTC
